### ISSUE TITLE
Splitting template/index.html in several components

### ISSUE THREAD

**Issue by nmezzopera** [Vue-with-Don/static-to-vue#1]
As a first task please take a look at `template/index.html` is a big piece of static HTML, the task is to:

- Analyse the file
- List out what part of it should be extracted and made a standalone component
- Once the list is final and you have a consensus on it actually create those components by splitting among the participants
- Each created component should only include HTML (we will deal with the javascript later) and should be submitted to the repo in its own PR

When thinking about what is a component and  how to chop that big file always keep in consideration [KISS](https://en.wikipedia.org/wiki/KISS_principle) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

Please use this issue to discuss among yourselves and to iterate on this task

**Comment by egentilucci** [comment]
Hi everybody, first of all thank you @DonNicoJs :), I'll try to start proposing my analysis on the matter.

In this comment I will address each chunk of code using the same comment tag you'll find in the file (i.e. `<!-- Header -->` for the Header and so on).

I would like to propose to leave the navbar (`<!-- Header -->` and `<!-- Menu -->`) and the footer (the last part of the `<!-- Footer -->`) inside the main component (App.vue), since they will appear in every page.

Navbar:
![image](https://user-images.githubusercontent.com/28620378/96373295-dead3c00-116b-11eb-85f3-5f9a0b7aad58.png)

Footer:
![image](https://user-images.githubusercontent.com/28620378/96373232-6777a800-116b-11eb-97dd-2b5232c25860.png)

There actually is one difference with the navbar though. On the main page the menu is visible but the logo with the navbar appears only past the title part.

Title:
![image](https://user-images.githubusercontent.com/28620378/96373422-96424e00-116c-11eb-80e0-7ce0791ddd70.png)

I don't how to address this while keeping the navbar inside the main component. So I ask you if in this case it would be better to keep the navbar as a separate component?

Beside this, I would split everything else into 4 reusable components: **Title**, **Spotlight**, **Features**, **Form** (apart from **Form** and **Title**, for the other names I chose the name css class assigned to them because right now I couldn't come up with something better and more meaningful but please feel free to propose different names :D).

---

Component #1 - **Title**:
- `<!-- Banner -->` lines 46 to 56. I would keep this in a separate component because it appears only in the main page.

![image](https://user-images.githubusercontent.com/28620378/96373422-96424e00-116c-11eb-80e0-7ce0791ddd70.png)

---

Component #2 - **Spotlight**:
- `<!-- Wrapper -->` (parts `<!-- One -->`, `<!-- Two -->` and `<!-- Three -->` will be created with a loop) lines 60 to 112.

![image](https://user-images.githubusercontent.com/28620378/96373632-1e752300-116e-11eb-9dff-2bbd68c9342c.png)

---

Component #3 - **Features**:
- `<!-- Wrapper -->` (part `<!-- Four -->`, all the articles (`<Article>`) will be created with a loop) lines 114 to 175.

![image](https://user-images.githubusercontent.com/28620378/96373651-44022c80-116e-11eb-9ae6-a3b8f031ebf9.png)

---

Component #4 - **Form**:
- `<!-- Footer -->` lines 177 to 232 excluding the footer (lines 226 to 229) since I proposed to keep it on the main page.

![image](https://user-images.githubusercontent.com/28620378/96373659-4cf2fe00-116e-11eb-9fe5-edd5988e184e.png)

---

Let me know your opinion and have a good day!!!

**Comment by Arienlys** [comment]
Hello!
Time for me to analyse too, and here my version of this website!
like @Culdred, i'll address each part with the comment tag. it's easier this way.
I'm sorry for any mistake or strange sentences, don't hesitate to correct me.

<hr>

_Components #1 & #2 - **Header**:_

I agree with the `<!-- Header -->` and the `<!-- Footer -->` as our first separate elements and... yeah, probably on the App.vue since they don't move.

Actually, i'll also separate the navbar (`<!-- Menu -->`) from the header too, so it will be simplier to modify it (both the content and the style) if needed. I think?
It will also help to control the fact that the header stay on screen (with an opacity effect)

_Components #3 & #4 - **Footer**:_
I'll also separate the footer. Since the `<h2>` and `<p>` tag are simple text, it will stay in the footer.vue. The form (the... `<form>` tag) will got his own component. I hesitated on separate the contact part (the `<ul class="contact">`). But since the footer don't have much and i don't see a page where the contact stuff is needed, it's probably better to simply add it to the footer.

_Edit_: actually, even if the contact got its own page, it seem meaningless to create a component only for this. But then it is really necessary to separate the form too. I thought it was needed but the more i think about this, the more i question myself.

<hr>

_Components #5 - **the Body itself**:_
Then the whole index page will have its own .vue file later. In which i'll put the basic text (`<h2>` and `<p>` tag, here we go again)
i'll also put the `<!-- Banner -->` in it, since i don't see any specific data's manipulation needed here.

_Components #6 - **the first part of the Wrapper**:_
i agree with this the `<!-- Wrapper -->` (parts `<!-- One -->`, `<!-- Two -->` and `<!-- Three -->`). I don't have much to say on this.

_Components #7 - **the cards**:_
Created with a loop too, the cards themself rather than the whole bloc, since the text part is already in the general part.

<hr>

So i'll have this, at this point:

- Header
-->Navbar
- Body
-->The wrappers
-->The cards
- Footer
-->Form (?)

For a total of 6/7 components?

**Comment by egentilucci** [comment]
Hi @Arienlys, I'll try to summarize everything in order to be able to make a final decision together :)
Please correct me if I got something wrong.

**[Edit after discussing the matter on discord]**

---

In the **Main Vue page** we will have:
- the **Header** (`<!-- Header -->`), keeping the Navbar + Menu as a standalone component,
- the **Footer** (the bottommost part of the website, with the copyright info, `<ul class="copyright">`...`</ul>`).

---

The components will be:
- **Component #1**: Navbar + Menu,
- **Component #2**: Banner,
- **Component #3**: 1st part of the wrapper (the one with the circles),
- **Component #4**: 2nd part of the wrapper (the one with the cards),
- **Component #5**: Form,
- **Component #6**: Contact Info (addres, etc...).

Let me know what you think.
Have a good day!

**Comment by egentilucci** [comment]
As decided on the dedicated discord channel the components will be:
- Component #1 [**header-menu.vue**] assigned to @Culdred 
- Component #2 [**main-banner.vue**] assigned to @Arienlys 
- Component #3 [**main-spotlight.vue**] assigned to @Culdred 
- Component #4 [**main-article.vue**] assigned to @Arienlys 
- Component #5 [**footer-form.vue**] assigned to @Culdred 
- Component #6 [**footer-contact.vue**] assigned to @Arienlys

**Comment by egentilucci** [comment]
@DonNicoJs sorry maybe this is a dumb question but, on the last bullet-point of the issue you ask us to create the components with only the HTML inside, what about the styling? We will deal with it later?

**Comment by nmezzopera** [comment]
@Culdred Correct, the styling will be discussed in the next round of work :)

**Comment by nmezzopera** [comment]
@Culdred @Arienlys Good job! We can close this issue, all the work is completed!
